[package]
name = "acm-sync-manager"
version = "0.1.0"
edition = "2021"
default-run = "acm-sync-manager"
license = "Apache-2.0"
authors = ["Vincent Desjardins <vdesjardins@gmail.com>"]

[[bin]]
doc = false
name = "acm-sync-manager"
path = "src/main.rs"

[lib]
name = "acm_sync_manager"
path = "src/lib.rs"

[features]
default = []
telemetry = ["tonic", "opentelemetry-otlp"]

[dependencies]
futures = "0.3.17"
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread", "signal"] }
tokio-rustls = "0.23.2"
k8s-openapi = { version = "0.14.0", features = ["v1_22"], default-features = false }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
serde_yaml = "0.8.21"
chrono = { version = "0.4.19", features = ["serde"] }
thiserror = "1.0.29"
schemars = { version = "0.8.7", features = ["chrono"] }
tracing = "0.1.26"
tracing-subscriber = { version = "0.3.1", features = ["json", "env-filter"] }
tracing-opentelemetry = "0.16.0"
opentelemetry = { version = "0.16.0", features = ["trace", "rt-tokio"] }
opentelemetry-otlp = { version = "0.9.0", features = ["tokio"], optional = true }
prometheus = "0.13.0"
tonic = { version = "0.5.2", features = ["tokio-rustls"], optional = true }
aws-config = "0.6.0"
aws-sdk-acm = "0.6.0"
axum = { version = "0.4.5" }
tower-http = "0.2.1"

[dependencies.kube]
version = "0.69.0"
features = ["runtime", "client", "derive", "rustls-tls"]
