[package]
name = "acm-sync-manager"
version = "0.2.0"
edition = "2021"
default-run = "acm-sync-manager"
license = "Apache-2.0"
authors = ["Vincent Desjardins <vdesjardins@gmail.com>"]

[[bin]]
doc = false
name = "acm-sync-manager"
path = "src/main.rs"

[lib]
name = "acm_sync_manager"
path = "src/lib.rs"

[features]
default = []
telemetry = ["tonic", "opentelemetry-otlp"]

[dependencies]
futures = "0.3.31"
tokio = { version = "1.43.0", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
tokio-rustls = "0.26.1"
k8s-openapi = { version = "0.24.0", features = [
    "v1_32",
], default-features = false }
actix-web = "4.9.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
serde_yaml = "0.9.34"
chrono = { version = "0.4.39", features = ["serde"] }
thiserror = "2.0.11"
schemars = { version = "0.8.21", features = ["chrono"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["json", "env-filter"] }
tracing-opentelemetry = "0.30.0"
opentelemetry = { version = "0.29.1", features = ["trace"] }
opentelemetry-otlp = { version = "0.29.0", features = [
    "tokio",
], optional = true }
opentelemetry_sdk = { version = "0.29.0", features = ["rt-tokio"] }
prometheus = "0.14.0"
tonic = { version = "0.13.0", features = ["transport"], optional = true }
aws-config = "1.5.15"
aws-sdk-acm = "1.58.0"
axum = { version = "0.8.1" }
tower-http = "0.6.2"
clap = { version = "4.5.27", features = ["derive"] }
anyhow = "1.0.95"
prometheus-client = "0.23.1"

[dependencies.kube]
features = ["runtime", "client", "derive", "rustls-tls", "aws-lc-rs"]

version = "0.99.0"
[dev-dependencies]
anyhow = "1.0.95"
