[package]
name = "acm-sync-manager"
version = "0.0.7"
edition = "2021"
default-run = "acm-sync-manager"
license = "Apache-2.0"
authors = ["Vincent Desjardins <vdesjardins@gmail.com>"]

[[bin]]
doc = false
name = "acm-sync-manager"
path = "src/main.rs"

[lib]
name = "acm_sync_manager"
path = "src/lib.rs"

[features]
default = []
telemetry = ["tonic", "opentelemetry-otlp"]

[dependencies]
futures = "0.3.21"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread", "signal"] }
tokio-rustls = "0.23.3"
k8s-openapi = { version = "0.14.0", features = ["v1_22"], default-features = false }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_yaml = "0.8.23"
chrono = { version = "0.4.19", features = ["serde"] }
thiserror = "1.0.30"
schemars = { version = "0.8.8", features = ["chrono"] }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.10", features = ["json", "env-filter"] }
tracing-opentelemetry = "0.17.2"
opentelemetry = { version = "0.17.0", features = ["trace", "rt-tokio"] }
opentelemetry-otlp = { version = "0.10.0", features = ["tokio"], optional = true }
prometheus = "0.13.0"
tonic = { version = "0.7.0", features = ["tokio-rustls"], optional = true }
aws-config = "0.9.0"
aws-sdk-acm = "0.9.0"
axum = { version = "0.5.0" }
tower-http = "0.2.5"
clap = { version = "3.1.8", features = ["derive"] }

[dependencies.kube]
version = "0.70.0"
features = ["runtime", "client", "derive", "rustls-tls"]

[dev-dependencies]
anyhow = "1.0.56"
