[package]
name = "acm-sync-manager"
version = "0.0.7"
edition = "2021"
default-run = "acm-sync-manager"
license = "Apache-2.0"
authors = ["Vincent Desjardins <vdesjardins@gmail.com>"]

[[bin]]
doc = false
name = "acm-sync-manager"
path = "src/main.rs"

[lib]
name = "acm_sync_manager"
path = "src/lib.rs"

[features]
default = []
telemetry = ["tonic", "opentelemetry-otlp"]

[dependencies]
futures = "0.3.25"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread", "signal"] }
tokio-rustls = "0.23.4"
k8s-openapi = { version = "0.16.0", features = ["v1_22"], default-features = false }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
serde_yaml = "0.9.14"
chrono = { version = "0.4.22", features = ["serde"] }
thiserror = "1.0.37"
schemars = { version = "0.8.11", features = ["chrono"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json", "env-filter"] }
tracing-opentelemetry = "0.18.0"
opentelemetry = { version = "0.18.0", features = ["trace", "rt-tokio"] }
opentelemetry-otlp = { version = "0.11.0", features = ["tokio"], optional = true }
prometheus = "0.13.3"
tonic = { version = "0.8.2", features = ["tokio-rustls"], optional = true }
aws-config = "0.51.0"
aws-sdk-acm = "0.21.0"
axum = { version = "0.5.17" }
tower-http = "0.3.4"
clap = { version = "4.0.6", features = ["derive"] }

[dependencies.kube]
version = "0.76.0"
features = ["runtime", "client", "derive", "rustls-tls"]

[dev-dependencies]
anyhow = "1.0.66"
