{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
  name: {{ include "acm-sync-manager.fullname" . }}
spec:
  endpoints:
    - path: /metrics
      port: http-metrics
      scheme: http
  selector:
    matchLabels:
      {{- include "acm-sync-manager.selectorLabels" . | nindent 4 }}
{{- end }}
