apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-leader-election-role
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-manager-role
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-metric-reader
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-proxy-role
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "acm-sync-manager.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "acm-sync-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-manager-rolebinding
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "acm-sync-manager.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "acm-sync-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-proxy-rolebinding
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "acm-sync-manager.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "acm-sync-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-controller-manager-metrics-service
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
