apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-leader-election-role
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  - "events.k8s.io"
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-manager-role
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - "events.k8s.io"
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-metric-reader
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "acm-sync-manager.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "acm-sync-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-manager-rolebinding
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "acm-sync-manager.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "acm-sync-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
