apiVersion: v1
kind: Service
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-health
      port: {{ .Values.service.port }}
      targetPort: http-health
      protocol: TCP
    - name: http-metrics
      port: {{ .Values.service.metrics.port }}
      protocol: TCP
      targetPort: http-metrics
  selector:
    {{- include "acm-sync-manager.selectorLabels" . | nindent 4 }}
