apiVersion: v1
kind: Service
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "acm-sync-manager.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acm-sync-manager.fullname" . }}-controller-manager-metrics-service
  labels:
    {{- include "acm-sync-manager.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 80
    protocol: TCP
    targetPort: http-metrics
  selector:
    control-plane: controller-manager
